# Generated by Django 2.2.1 on 2019-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=256, null=True)),
                ('work', models.CharField(blank=True, max_length=256, null=True)),
                ('fnlwgt', models.CharField(blank=True, max_length=256, null=True)),
                ('education', models.CharField(max_length=256)),
                ('education_num', models.CharField(blank=True, max_length=256, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=256, null=True)),
                ('occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('relationship', models.CharField(blank=True, max_length=256, null=True)),
                ('race', models.CharField(blank=True, max_length=256, null=True)),
                ('sex', models.CharField(blank=True, max_length=256, null=True)),
                ('capital_gain', models.CharField(blank=True, max_length=256, null=True)),
                ('capital_loss', models.CharField(blank=True, max_length=256, null=True)),
                ('hours_per_week', models.CharField(blank=True, max_length=256, null=True)),
                ('native_country', models.CharField(blank=True, max_length=256, null=True)),
                ('salary', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
